### ISSUE TITLE
TypeError: Cannot read property 'connection' of undefined

### ISSUE THREAD

**Issue by Hunam6** [railwayapp-starters/ghost#7]
When initiating a project with this starter, here's what I get:
```js
$ node index.js
TypeError: Cannot read property 'connection' of undefined
at Object.sanitizeDatabaseProperties (/workspace/node_modules/ghost/core/shared/config/utils.js:62:25)
at Object.loadNconf (/workspace/node_modules/ghost/core/shared/config/loader.js:53:16)
at Object.<anonymous> (/workspace/node_modules/ghost/core/shared/config/index.js:3:25)
at Module._compile (internal/modules/cjs/loader.js:1085:14)
at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
at Module.load (internal/modules/cjs/loader.js:950:32)
at Function.Module._load (internal/modules/cjs/loader.js:790:12)
at Module.require (internal/modules/cjs/loader.js:974:19)
at require (internal/modules/cjs/helpers.js:101:18)
at bootGhost (/workspace/node_modules/ghost/core/boot.js:350:18)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by cursecodes** [comment]
I am also having this issue.

**Comment by Compositr** [comment]
Did you try switching buildpacks from Heroku to Paketo? I tried that and it resolved itself for me.

**Comment by FarazPatankar** [comment]
This has been resolved since this issue was created. I am closing this for now but feel free to re-open if you still see it on either buildpack.
